#christmastree
print("                 *                  ")
print("                ***                 ")
print("               *****                ")
print("              *******               ")
print("             *********              ")
print("            ***********             ")
print("           *************            ")
print("          ***************           ")
print("         *****************          ")
print("                 ||                 ")
print("                 ||                 ")  
print("                 ||                 ")   
print("                 ||                 ")  
print("_________________||_________________")  